name: ebayfetchsold
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - flask=2.2.5
  - werkzeug=2.2.3
  - pandas
  - selenium
  - beautifulsoup4
  - python-dateutil
  - pip:
    - webdriver-manager 